version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    #build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  
  ms-criptcoin-vote:
    image: moisesba/ms-criptcoin-vote
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - zookeeper
      - kafka
      - mongo  
    environment:
      MONGO_SERVER_URL: mongodb://mongo:27017
      KAFKA_BROKER_URL: kafka:9092
    #  MONGO_USER: root
    #  MONGO_PASSWORD: example
    #  KAFKA_VOTE_TOPIC: vote_topic
    #  JWT_PASSWORD: chave_jwt     