version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    #build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  
  ms-criptcoin-vote:
    image: moisesba/s-criptcoin-vote
    restart: always
    ports:
      - 9090:9090
    #environment:
    #  MONGO_SERVER_URL: 
    #  MONGO_USER:
    #  MONGO_PASSWORD:
    #  KAFKA_BROKER_URL:
    #  KAFKA_VOTE_TOPIC:
    #  JWT_PASSWORD:      