// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package criptcoinvote

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CriptCoinVoterApiClient is the client API for CriptCoinVoterApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CriptCoinVoterApiClient interface {
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error)
	UnVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error)
}

type criptCoinVoterApiClient struct {
	cc grpc.ClientConnInterface
}

func NewCriptCoinVoterApiClient(cc grpc.ClientConnInterface) CriptCoinVoterApiClient {
	return &criptCoinVoterApiClient{cc}
}

func (c *criptCoinVoterApiClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error) {
	out := new(VoteReply)
	err := c.cc.Invoke(ctx, "/criptcoinvote.CriptCoinVoterApi/vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *criptCoinVoterApiClient) UnVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error) {
	out := new(VoteReply)
	err := c.cc.Invoke(ctx, "/criptcoinvote.CriptCoinVoterApi/unVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CriptCoinVoterApiServer is the server API for CriptCoinVoterApi service.
// All implementations must embed UnimplementedCriptCoinVoterApiServer
// for forward compatibility
type CriptCoinVoterApiServer interface {
	Vote(context.Context, *VoteRequest) (*VoteReply, error)
	UnVote(context.Context, *VoteRequest) (*VoteReply, error)
	mustEmbedUnimplementedCriptCoinVoterApiServer()
}

// UnimplementedCriptCoinVoterApiServer must be embedded to have forward compatible implementations.
type UnimplementedCriptCoinVoterApiServer struct {
}

func (UnimplementedCriptCoinVoterApiServer) Vote(context.Context, *VoteRequest) (*VoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}
func (UnimplementedCriptCoinVoterApiServer) UnVote(context.Context, *VoteRequest) (*VoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnVote not implemented")
}
func (UnimplementedCriptCoinVoterApiServer) mustEmbedUnimplementedCriptCoinVoterApiServer() {}

// UnsafeCriptCoinVoterApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CriptCoinVoterApiServer will
// result in compilation errors.
type UnsafeCriptCoinVoterApiServer interface {
	mustEmbedUnimplementedCriptCoinVoterApiServer()
}

func RegisterCriptCoinVoterApiServer(s grpc.ServiceRegistrar, srv CriptCoinVoterApiServer) {
	s.RegisterService(&CriptCoinVoterApi_ServiceDesc, srv)
}

func _CriptCoinVoterApi_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CriptCoinVoterApiServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/criptcoinvote.CriptCoinVoterApi/vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CriptCoinVoterApiServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CriptCoinVoterApi_UnVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CriptCoinVoterApiServer).UnVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/criptcoinvote.CriptCoinVoterApi/unVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CriptCoinVoterApiServer).UnVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CriptCoinVoterApi_ServiceDesc is the grpc.ServiceDesc for CriptCoinVoterApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CriptCoinVoterApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "criptcoinvote.CriptCoinVoterApi",
	HandlerType: (*CriptCoinVoterApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "vote",
			Handler:    _CriptCoinVoterApi_Vote_Handler,
		},
		{
			MethodName: "unVote",
			Handler:    _CriptCoinVoterApi_UnVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "criptcoinvote.proto",
}
